import './globals.css'
import { Inter } from 'next/font/google'
import './styles.css'

//@ts-ignore
global.performance = global.performance || {
  now: () => new Date().getTime(),
};

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preload"
          href="/fonts/waterlily.regular.ttf"
          as="font"
          crossOrigin=""
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
